damda/ai/urls.py
from django.urls import path
from .import views

from django.conf.urls.static import static
from django.conf import settings


app_name = "ai"
urlpatterns = [
    path('', views.index, name='index'),
    path('name-form/', views.name_form, name='name-form'),
    path('name-result/', views.name_result, name='name-result'),
    path('feel-form/', views.feel_form, name='feel-form'),
    path('feel-result/', views.feel_result, name='feel-result'),
    path('quiz-form/', views.quiz_form, name='quiz-form'),
    path('quiz-result/', views.quiz_result, name='quiz-result'),
    path('problem-form/', views.problem_form, name='problem-form'),
    path('problem-result/', views.problem_result, name='problem-result'),
    path('face01-form/', views.face01_form, name='face01-form'),
    path('face01-result/', views.face01_result, name='face01-result'),
    path('face02-form/', views.face02_form, name='face02-form'),
    path('face02-result/', views.face02_result, name='face02-result'),
    path('draw-form/', views.draw_form, name='draw-form'),
    path('draw-result/', views.draw_result, name='draw-result'),
    path('result/', views.result, name='result'),
    path('video', views.video, name='video'),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:  # new
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

damda/damda/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ai.urls')),
]

damda/ai/models.py
from django.db import models


class Dam(models.Model):
    canvas = models.ImageField(upload_to='uploads/%Y/%m/%d/', blank=True)
    
    def __str__(self):
        return self.user_name

damda/ai/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.http import HttpResponse, StreamingHttpResponse
from django.template.loader import render_to_string

import random
import cv2, time
import threading

from ai.find_problem import find_problem
from ai.face_predict import face_prediction


def index(request):
    return render(request, 'index.html')


def name_form(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        if username != '':
            request.session['username'] = username
            return redirect('ai:name-result')

    return render(request, 'name_form.html')


def name_result(request):
    request.session['red'] = 0
    request.session['green'] = 0
    request.session['blue'] = 0
    request.session['quizStage'] = 1
    request.session['quizPoint'] = 0
    return render(request, 'name_result.html')


def feel_form(request):
    if request.method == 'POST':
        feel = request.POST.get('feel')
        if feel != '':
            request.session['feel'] = feel

    return HttpResponse(status=204)


def feel_result(request):
    return render(request, 'feel_result.html')


def quiz_form(request):
    quizValue = {
      1: [0, -1, 1],
      2: [-1, 1, 0],
      3: [1, 0, -1],
      4: [0, 1, -1],
      5: [-1, 1, 0],
      6: [1, 0, -1],
      7: [-1, 0, 1],
      8: [1, -1, 0],
      9: [1, 0, -1],
      10: [1, -1, 0],
    }

    if request.method == 'POST':
        quizPoint = request.POST.get('quizPoint')
        if quizPoint is not None and request.session['quizStage'] < 11:
            request.session['quizStage'] = request.session['quizStage'] + 1
            request.session['quizPoint'] = request.session['quizPoint'] +int(quizPoint)
            return HttpResponse(status=204)

    context = {'quizValue': quizValue}
    return render(request, 'quiz_form.html', context)


def quiz_result(request):
    soloType = [2, 5, 9]
    soloObj = {
      2: {1: '달', 2: '사람얼굴', 3: '나비'},
      5: {1: '여성', 2: '나무', 3: '그외'},
      9: {1: '입술', 2: '나무', 3: '뿌리'},
    }
    quizScript = {
      1: '다음 그림 중 가장 마음에 드는 그림을 골라주세요.',
      2: '다음 그림에서 무엇이 먼저 보이시나요?',
      3: '다음 그림 중 가장 행복해 보이는 그림을 고르세요.',
      4: '다음 그림 중 인간관계를 가장 잘 표현한 그림은 무엇인가요?',
      5: '다음 그림에서 무엇이 먼저 보이시나요?',
      6: '다음 사진 중 가장 힘들어 보이는 사람은 누구인가요?',
      7: '다음 사진 중 평소 당신의 표정은 어떤가요?',
      8: '다음 사진 중 가장 마음에 드는 생일 날 사진은 무엇인가요?',
      9: '다음 그림에서 무엇이 먼저 보이시나요?',
      10: '가장 마음에 드는 그림을 골라주세요.',

    }
    
    if request.session['quizStage'] in soloType:
      quizType = 'solo'
    else:
      quizType = 'triple'

    context = {
      'quizType': quizType,
      'soloObj': soloObj,
      'quizScript': quizScript,
    }
    return render(request, 'quiz_result.html', context)


def problem_form(request):
    if request.method == 'POST':
        problem = request.POST.get('problem')
        problem_result = find_problem(problem)
        print(problem_result)
        if problem_result != '':
            request.session['problem'] = problem
            request.session['problem_result'] = problem_result
        else:
            request.session['problem_result'] = 'default'

        return HttpResponse(status=204)

    return render(request, 'problem_form.html')


def problem_result(request):
    return render(request, 'problem_result.html')


def face01_form(request):
    answer , red, green, blue = face_prediction('./ai/best_model(cpu).pkl',r'./ai/haarcascade_frontalface_default.xml')

    request.session['red'] = red
    request.session['green'] = green
    request.session['blue'] = blue

    if answer == 'positive':
      request.session['emotion01'] = True
    else: 
      request.session['emotion01'] = False

    return render(request, 'face01_form.html')


def face01_result(request):
    return render(request, 'face01_result.html')


def face02_form(request):
    answer , red, green, blue = face_prediction('./ai/best_model(cpu).pkl',r'./ai/haarcascade_frontalface_default.xml')

    request.session['red'] = red
    request.session['green'] = green
    request.session['blue'] = blue

    if answer == 'positive':
      request.session['emotion02'] = True
    else: 
      request.session['emotion02'] = False
    return render(request, 'face02_form.html')


def face02_result(request):
    return render(request, 'face02_result.html')


def draw_form(request):
    return render(request, 'draw_form.html')


def draw_result(request):
    return render(request, 'draw_result.html')


def result(request):
    return render(request, 'result.html')


def stream():
    cap = cv2.VideoCapture(0) 

    while True:
        ret, frame = cap.read()

        if not ret:
            print('Error: failed to capture image')
            break

        cv2.imwrite('demo.jpg', frame)
        yield (b'--frame\r\n'
               b'Content-Type: image/jpeg\r\n\r\n' + open('demo.jpg', 'rb').read() + b'\r\n')


def video(request):
        try:
            time.sleep(2)
            return StreamingHttpResponse(stream(), content_type='multipart/x-mixed-replace; boundary=frame')
        except HttpResponseServerError as e:
            print('asborted', e)

damda/ai/templates/canvas_intro.html
{% extends 'home.html' %}
{% load static %}

{% block content %}
<p>
  지금까지 당신의 이야기를 들려줘서 고마워요!<br>
  <br>
  마지막으로,<br>
  자신이 생각하는 자신을 그림으로 그려서 담아볼까요?
</p>

<a href="{% url 'ai:canvas-result' %}" class="space-link">space 키를 누르면 다음으로 넘어갑니다.</a>
{% endblock content %}

damda/ai/templates/draw_form.html
{% load static %}
{% block form %}
<span class="cur-stage" style="display: none">draw</span>
<span class="next-stage" style="display: none">result</span>

<!-- Modal -->
<div class="modal fade show" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
  aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="article-header">
        <div class="btn-wrap | d-flex">
          <button class="btn-red"></button>
          <button class="btn-green"></button>
          <button class="btn-blue"></button>
        </div>
      </div>
      <div class="canvas-wrap">
        <canvas id="canvas" width="557" height="502"></canvas>
        <input class="btn-submit" data-bs-dismiss="modal" aria-label="Close" type="submit" value="담기">
      </div>
    </div>
  </div>
</div>

<script>
  $('.btn-submit').css('pointer-events', 'none');

  setTimeout(function () {
    $('.btn-submit').css('pointer-events', 'auto');
  }, 5000);

  $('.btn-submit').on('click', function () {
    $(this).css('pointer-events', 'none');
    setTimeout(function () {
      $('.btn-submit').css('pointer-events', 'auto');
    }, 1000);
    if ($('form textarea').val() === '') {
      return false;
    }

    var curStage = $('.cur-stage').text();
    var nextStage = $('.next-stage').text();

    setTimeout(function () {
      $.ajax({
        url: `/${curStage}-result`,
        success: function (data) {
          $('.article-body').append(data);
          setPush();
        }
      });

      $.ajax({
        url: `/${nextStage}`,
        success: function (data) {
          $('.article-footer').html(data);
        }
      });

      $('.article-body').animate({
        scrollTop: $('.article-body').get(0).scrollHeight
      }, 500);
    }, 250)
  });

  var rsRed = {{ request.session.red }} === 0 ? 1 : {{ request.session.red }};
  var rsGreen = {{ request.session.green }} === 0 ? 1 : {{ request.session.green }};
  var rsBlue = {{ request.session.blue }} === 0 ? 1 : {{ request.session.blue }};
  rsRed = Math.floor((rsRed / (rsRed + rsGreen + rsBlue)) * 255)
  rsGreen = Math.floor((rsGreen / (rsRed + rsGreen + rsBlue)) * 255)
  rsBlue = Math.floor((rsBlue / (rsRed + rsGreen + rsBlue)) * 255)

  const canvas = document.querySelector("#canvas");
  const ctx = canvas.getContext("2d");
  ctx.lineWidth = 25;
  ctx.lineCap = "round";
  ctx.strokeStyle = `rgb(${rsRed}, ${rsGreen}, ${rsBlue})`;

  const draw = e => {
    const x = e.offsetX;
    const y = e.offsetY;
    if (!drawing) return;
    ctx.beginPath();
    ctx.moveTo(x, y);
    ctx.lineTo(x, y);
    ctx.stroke();
  };

  let drawing = false; //기본상태는 대기상태
  canvas.addEventListener("mousedown", () => (drawing = true)); // 드로잉 끝
  canvas.addEventListener("mouseup", () => (drawing = false)); // 드로잉 대기
  canvas.addEventListener("mousemove", draw);
</script>
{% endblock form %}

damda/ai/templates/face01_form.html
{% load static %}
{% block form %}
<span class="cur-stage" style="display: none">face01</span>
<span class="next-stage" style="display: none">face02</span>

<!-- Modal -->
<div class="modal fade show" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
  aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="article-header">
        <div class="btn-wrap | d-flex">
          <button class="btn-red"></button>
          <button class="btn-green"></button>
          <button class="btn-blue"></button>
        </div>
      </div>
      <div id="video">
        <img src="{% url 'ai:video' %}" width="557px" height="502px">
        <input class="btn-submit" data-bs-dismiss="modal" aria-label="Close" type="submit" value="담기">
      </div>
    </div>
  </div>
</div>

<script>
  $('.btn-submit').css('pointer-events', 'none');

  setTimeout(function () {
    $('.btn-submit').css('pointer-events', 'auto');
  }, 3000);

  $('.btn-submit').on('click', function () {
    $(this).css('pointer-events', 'none');
    setTimeout(function () {
      $('.btn-submit').css('pointer-events', 'auto');
    }, 1000);
    if ($('form textarea').val() === '') {
      return false;
    }

    var curStage = $('.cur-stage').text();
    var nextStage = $('.next-stage').text();

    setTimeout(function () {
      $.ajax({
        url: `/${curStage}-result`,
        success: function (data) {
          $('.article-body').append(data);
          setPush();
        }
      });

      $.ajax({
        url: `/${nextStage}-form`,
        success: function (data) {
          $('.article-footer').html(data);
        }
      });

      $('.article-body').animate({
        scrollTop: $('.article-body').get(0).scrollHeight
      }, 500);
    }, 250)
  });
</script>
{% endblock form %}

damda/ai/templates/face02_form.html
{% load static %}
{% block form %}
<span class="cur-stage" style="display: none">face02</span>
<span class="next-stage" style="display: none">draw</span>

<!-- Modal -->
<div class="modal fade show" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
  aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="article-header">
        <div class="btn-wrap | d-flex">
          <button class="btn-red"></button>
          <button class="btn-green"></button>
          <button class="btn-blue"></button>
        </div>
      </div>
      <div id="video">
        <img src="{% url 'ai:video' %}" width="557px" height="502px">
        <input class="btn-submit" data-bs-dismiss="modal" aria-label="Close" type="submit" value="담기">
      </div>
    </div>
  </div>
</div>

<script>
  $('.btn-modal').on('click', function () {
    $('.modal-loading').css('display', 'flex');
    $('p.hidden').removeClass('hidden');
    $(".article-body").animate({
      scrollTop: $('.article-body').get(0).scrollHeight
    }, 500);

    setTimeout(function () {
      $('.modal-loading').fadeOut(500);
      $('.modal').modal('show');
    }, 5000);
  });

  $('.btn-submit').css('pointer-events', 'none');

  setTimeout(function () {
    $('.btn-submit').css('pointer-events', 'auto');
  }, 3000);

  $('.btn-submit').on('click', function () {
    $(this).css('pointer-events', 'none');
    setTimeout(function () {
      $('.btn-submit').css('pointer-events', 'auto');
    }, 1000);
    if ($('form textarea').val() === '') {
      return false;
    }

    var curStage = $('.cur-stage').text();
    var nextStage = $('.next-stage').text();

    setTimeout(function () {
      $.ajax({
        url: `/${curStage}-result`,
        success: function (data) {
          $('.article-body').append(data);
          setPush();
        }
      });

      $.ajax({
        url: `/${nextStage}-form`,
        success: function (data) {
          $('.article-footer').html(data);
        }
      });

      $('.article-body').animate({
        scrollTop: $('.article-body').get(0).scrollHeight
      }, 500);
    }, 250)
  });
</script>
{% endblock form %}

damda/ai/templates/feel_result.html
{% load static %}
{% block content %}
<p class="guest">
  {{ request.session.feel }}
</p>

<p class="host">
  당신의 기분을 알려줘서 고마워요.<br>
  먼저 상담을 하기 전에 간단한 심리 테스트를 해보려고 해요.<br>
  가벼운 마음으로 해볼까요?
</p>

<p class="host">
  &#60;심리 테스트&#62;<br>
  이 심리 테스트는 질문에 따라 자신의 생각과 맞는 사진을 고르는 테스트입니다.<br>
  질문은 총 10개로, 사진에 따라 점수가 주어집니다.<br>
  테스트를 통해 여러분의 최근 심리상태를 확인해보세요.
</p>

<p class="host">
  [질문 {{ request.session.quizStage }}]<br>
  다음 그림 중 가장 마음에 드는 그림을 고르세요.<br>
  <span class="row text-center">
    <span class="col-4"><img class="w-100" src="/static/img/{{ request.session.quizStage }}-1.jpg" alt="">(1)</span>
    <span class="col-4"><img class="w-100" src="/static/img/{{ request.session.quizStage }}-2.jpg" alt="">(2)</span>
    <span class="col-4"><img class="w-100" src="/static/img/{{ request.session.quizStage }}-3.jpg" alt="">(3)</span>
  </span>
</p>
{% endblock content %}

damda/ai/templates/name_form.html
{% extends 'home.html' %}

{% load static %}
{% block content %}
<section id="main" class="main-intro | d-flex justify-content-center align-items-center">
  <article id="intro" class="d-flex flex-column justify-content-center text-center">
    <div class="position-relative mb-36">
      <img class="bg-box" src="{% static '/img/bg_box_black.svg' %}" alt="">

      <form method="POST" action="{% url 'ai:name-form' %}" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="input-wrap mb-36">
          <span class="d-block mb-36 text-white"
            style="font-family: 'Garam'; font-weight: 400; font-size: 30px; line-height: 36px;">
            당신의 이름을 담아주세요.
          </span>
          <input id="your_name" class="input-half" type="text" name="username" maxlength="100" required>
        </div>
        <div class="input-wrap">
          <input class="btn-submit m-auto" type="submit" value="담기">
        </div>
      </form>
    </div>
  </article>
</section>
{% endblock content %}

damda/ai/templates/name_result.html
{% extends 'home.html' %}
{% load static %}

{% block content %}
<p class="host">
  안녕하세요, 저는 유영훈이에요.<br>
  지금부터 여러 질문을 통해 비어있는 당신의 상자를 담아보려고 해요.<br>
  여러분의 마음을 잘 들여다보고 답해주세요.
</p>

<p class="host">
  당신의 이름은 {{ request.session.username }}이군요. 이렇게 만나게 되어서 정말 반가워요.<br>
  오늘 기분은 어떠한지 말해줄 수 있나요?<br>
  그리고 그 기분의 이유도 같이 말해주세요.
</p>
{% endblock content %}


{% block form %}
<form method="POST" action="{% url 'ai:feel-form' %}" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="textarea-wrap">
    <textarea id="input-feel" name="feel" cols="30" rows="10"></textarea>
  </div>

  <input class="btn-submit" type="submit" value="담기">
</form>
{% endblock form %}

damda/ai/templates/quiz_form.html
{% block form %}
<form method="POST" action="{% url 'ai:quiz-form' %}" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="d-flex justify-content-center align-items-center">
    <div class="input-wrap m-5">
      <input type="radio" name="quizPoint" id="q-1-z">
      <label for="q-1-z">(1)</label>
    </div>
    <div class="input-wrap m-5">
      <input type="radio" name="quizPoint" id="q-1-m">
      <label for="q-1-m">(2)</label>
    </div>
    <div class="input-wrap m-5">
      <input type="radio" name="quizPoint" id="q-1-p">
      <label for="q-1-p">(3)</label>
    </div>
  </div>

  <input class="btn-submit" type="submit" value="담기">
</form>

<script>
  var quizStage = {{ request.session.quizStage }};
  var quizValue = {{ quizValue }};

  $('input[type="radio"]').each(function (index) {
    $(this).val(quizValue[quizStage][index]);
  });

  $('.btn-submit').on('click', function () {
    $(this).css('pointer-events', 'none');
    setTimeout(function () {
      $('.btn-submit').css('pointer-events', 'auto');
    }, 1000);
    if (!$('input:radio[name=quizPoint]').is(':checked')) {
      return false;
    }

    var stage = ['feel', 'quiz', 'problem', 'face01', 'face02', 'draw'];
    var curStage = $('form').attr('action').match(/\/([^-]+)/)[1];
    var nextStage = stage[stage.indexOf(curStage) + 1];

    if (jQuery.inArray(curStage, stage) !== -1) {
      if (curStage.indexOf('quiz') != -1) {
        if (quizStage > 9) {
          nextStage = 'problem';
        } else {
          nextStage = 'quiz';
        }
      }

      setTimeout(function () {
        $.ajax({
          url: `/${curStage}-result`,
          success: function (data) {
            $('.article-body').append(data);
            setPush();
          }
        });

        $.ajax({
          url: `/${nextStage}-form`,
          success: function (data) {
            $('.article-footer').html(data);
          }
        });

        $(".article-body").animate({
          scrollTop: $('.article-body').get(0).scrollHeight
        }, 500);
      }, 250);
    };
  });
</script>
{% endblock form %}

damda/ai/templates/result.html
{% load static %}
{% block content %}
<div class="result-wrapper" style="display: none;">
  <section id="main" class="main-intro | d-flex justify-content-center align-items-center">
    <article id="intro" class="d-flex flex-column justify-content-center text-center">
      <div class="result-draw"></div>

      <h1 class="result-title">{{ request.session.username }}님의 담</h1>

      <svg xmlns="http://www.w3.org/2000/svg" width="1043" height="827" viewBox="0 0 1043 827" fill="none">
        <path id="colorBox"
          d="M1.5 179.33L518.099 372.364L518.648 372.569L519.191 372.348L1039.93 159.916V621.653L518.626 825.389L1.5 621.656V179.33Z"
          fill="rgb({{ request.session.red }},{{ request.session.green }},{{ request.session.blue }})" stroke="black"
          stroke-width="3" />
        <path d="M519.141 372.402V827" stroke="black" stroke-width="3" />
        <path
          d="M520.687 369.952L4.46425 177.438L520.741 1.57527L756.252 72.729L756.257 72.7303L1038.51 157.069L520.687 369.952Z"
          fill="white" stroke="black" stroke-width="3" />
      </svg>

      <div class="result-box | d-flex justify-content-between align-items-center">
        <div class="result-left">
          <p id="problem"></p>
          <p id="quote"></p>
        </div>
        <div class="result-right">
          <p id="quiz"></p>
          <p id="color">{{ hex_color }}</p>
        </div>
      </div>
    </article>
  </section>
</div>

<a class="link-root" href="{% url 'ai:index' %}"><img src="{% static '/img/icon_box.svg' %}" alt=""></a>

<script>
  setTimeout(function () {
    $('.result-wrapper').fadeIn(1000);
    $('.result-draw').html($('.canvas-result'));
  }, 5000);

  var rsRed = {{ request.session.red }} === 0 ? 1 : {{ request.session.red }};
  var rsGreen = {{ request.session.green }} === 0 ? 1 : {{ request.session.green }};
  var rsBlue = {{ request.session.blue }} === 0 ? 1 : {{ request.session.blue }};
  rsRed = Math.floor((rsRed / (rsRed + rsGreen + rsBlue)) * 255)
  rsGreen = Math.floor((rsGreen / (rsRed + rsGreen + rsBlue)) * 255)
  rsBlue = Math.floor((rsBlue / (rsRed + rsGreen + rsBlue)) * 255)

  function ColorToHex(color) {
    var hexadecimal = color.toString(16);
    return hexadecimal.length == 1 ? "0" + hexadecimal : hexadecimal;
  }
  function ConvertRGBtoHex(red, green, blue) {
    return ColorToHex(red) + ColorToHex(green) + ColorToHex(blue);
  }

  $('.result-right #color').text(ConvertRGBtoHex(rsRed, rsGreen, rsBlue));
  $('#colorBox').attr('fill', `#${ConvertRGBtoHex(rsRed, rsGreen, rsBlue)}`);

  var problemObj = {
    'default': '당신의 고민을 얘기해줘서 고마워요',
    'work': '당신의 진로에 관한 이야기 잘 들었어요',
    'love': '당신의 사랑을 응원해요',
    'money': '당신은 재정쪽에 관심이 많군요',
    'study': '학업에 대한 열정은 빛을 발할거예요',
    'health': '당신이 앞으로도 쭉 건강했으면 좋겠어요',
    'relationship': '인간 관계에 너무 힘들어하지 말아요',
  }
  $('#problem').text(problemObj['{{ request.session.problem_result }}']);

  var quote_list = [
    '열린 마음으로 기다려보아요.',
    '지금은 쉬어야 할 때예요.',
    '무시하지 말아요.',
    '인정할 필요가 있어요.',
    'PASS! 넘겨버리는 것도 좋은 방법이에요.',
    '살아있는 한 희망은 있어요.',
    '문제를 일으킬 것이 분명해요.',
    '지금 아니면 안돼요.',
    '처음 생각을 믿으세요.',
    '어느때보다 지금 가장 잘 알고 있어요.',
    '자신감을 가지고 리드해서 진행해주세요.',
    '실패할 리 없어요.',
    '어떻게 하든 결과는 길게 남게 돼요.',
    '접근 방식을 다시 생각해볼까요.',
    '세월이 약이에요.',
    '기쁜일이 다가오니 기다리세요.',
    '지금 당신에겐 휴식이 먼저예요.',
    '소신을 가지세요.',
    '일을 뒤로 미루지 말아요.',
    '염려하지 말아요.',
    '자신을 사랑하세요.',
    '상황이 좋지 않으니 일단 지켜보아요.',
    '좋은 게 좋은 거예요 좋은 쪽으로 생각하세요.',
    '가끔은 쉬는게 좋아요.',
    '먼저 다가가세요.',
    '서두르지 말아요.',
    '지금 생각을 쭉 가지고 있어주세요.',
    '잠시 쉬어도 돼요.',
    '한숨 자고 생각해보세요.',
    '시간이 약이에요.',
    '해가 뜨기 전 새벽이 가장 어두워요.',
    '먼 훗날의 당신은 그때의 당신을 절대로 잊지마세요.',
    '이럴 때일 수록 정신 차리는게 좋아요.',
    '이 또한 지나가리.',
    '행복만 가득하길 바라요.',
    '잠시 울어도 좋아요.',
    '지금은 힘들더라도 잘 해낼 수 있어요.',
    '앞으로도 그 모습 변치 않길 바라요.',
    '따뜻한 날만 가득하길 바라요.',
    '지금을 즐겨요.',
    '누구에게 기대도 좋아요.',
    '지금을 소중히 하길 바라요.',
    '지금 당신이 어디 서있든 넘어지지 말아요.',
    '편안한 밤을 보내길 바라요.',
    '오늘은 행운이 가득한 날이에요.',
    '앞으로 잘 할 수 있는 힘이 생길거예요.',
    '이 순간을 잊지 말고 기억해줘요.',
    '꼭 따라갈 필요 없어요.',
    '당신의 길을 나아가세요.',
    '천천히 나아가도 괜찮아요.',
    '주변의 말을 귀담아 듣지 않아도 돼요.',
    '지금 모습도 아름답고 멋져요.',
    '과거를 잊고 지금을 살아요.',
    '잘 지내길 바라요.',
    '걱정하지 말아요.',
    ' 좋아하는 것을 자주 하세요.',
    '당신이 가는 길이 부디 평안하길 빌어요.',
  ];
  $('#quote').text(quote_list[Math.floor(Math.random() * quote_list.length)]);

  var quizValue = $('.quiz-result').text();
  $('#quiz').text(quizValue);
</script>
{% endblock content %}